export default {
  about: '/',
  colors: '/colors',
  typography: '/typography',
  components: '/components',
  buttons: '/buttons',
  chips: '/chips',
  datepicker: '/date-picker',
  input: '/input',
  checkbox: '/checkbox',
  select: '/select',
  radio: '/radio',
  subHeader: '/sub-header',
  stickyNav: '/sticky-nav',
  shipmentModeIcon: '/shipment-mode-icon',
  colorPicker: '/color-picker',
  message: '/message',
  alert: '/alert',
  multiInput: '/multi-input',
  drawer: '/drawer',
};
